# Generated by Django 3.2.6 on 2021-09-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0002_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.CharField(max_length=100, null='not found'),
            preserve_default='not found',
        ),
    ]
