# Generated by Django 3.2.6 on 2021-09-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0004_alter_question_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_answer',
            field=models.CharField(default='No Answer Chosen', max_length=100, null='Not found'),
            preserve_default='Not found',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct',
            field=models.CharField(max_length=100, null='Not found'),
        ),
    ]
